<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calendar [
<!ELEMENT calendar (version, icalurl?, googleurl?, notes_list+, mult_type+, special_rule+, section+, band+, contest_series+, contest+)>
<!ELEMENT mult_type (name, description, long_description, exchange?, scoring_description?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT long_description (#PCDATA)>
<!ELEMENT band_list (#PCDATA)>
<!ELEMENT special_rule (name, description, long_description)>
<!ELEMENT section (name, description, long_description, power?, height?, singleantenna?, overall_section?)>
<!ELEMENT contest (name, description, short_description?, time_list+, section_list+, scoring, special_rules_list*, band_list+, mult?, mode?, iaru?, power?, award_list*, entry_date, override?)>
<!ELEMENT time_list (month_list+, ((start_day, start_week) | start_date_list+), start_time, time_type, duration, mult?)>
<!ELEMENT contest_series (name, description, contest_list+, section_list*, special_rules_list*, award_list*)>
<!ELEMENT month_list (#PCDATA)>
<!ELEMENT start_day (#PCDATA)>
<!ELEMENT start_week (#PCDATA)>
<!ELEMENT start_time (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT section_list (#PCDATA)>
<!ELEMENT scoring ((perkms) | (oneppq))>
<!ELEMENT scoring_description (#PCDATA)>
<!ELEMENT perkms (#PCDATA)>
<!ELEMENT special_rules_list (#PCDATA)>
<!ELEMENT reg1band (#PCDATA)>
<!ELEMENT band (name,  reg1band, wavelength, time_list?)>
<!ELEMENT freq (#PCDATA)>
<!ELEMENT power (#PCDATA)>
<!ELEMENT wavelength (#PCDATA)>
<!ELEMENT iaru (#PCDATA)>
<!ELEMENT mult (#PCDATA)>
<!ELEMENT mode (#PCDATA)>
<!ELEMENT contest_list (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT singleantenna (#PCDATA)>
<!ELEMENT exchange (#PCDATA)>
<!ELEMENT championship (#PCDATA)>
<!ELEMENT time_type (#PCDATA)>
<!ELEMENT oneppq (#PCDATA)>
<!ELEMENT award_list (#PCDATA)>
<!ELEMENT override (#PCDATA)>
<!ELEMENT entry_date (#PCDATA)>
<!ELEMENT start_date_list (#PCDATA)>
<!ELEMENT short_description (#PCDATA)>
<!ELEMENT overall_section (#PCDATA)>
<!ELEMENT icalurl (#PCDATA)>
<!ELEMENT googleurl (#PCDATA)>
<!ELEMENT notes_list (#PCDATA)>
<!ELEMENT version (#PCDATA)>
]>
<!-- RSGB VHF contest calendar and rules by G4CLA-->
<!-- Version 1 Initial version 21 Nov 2008 -->
<!-- 23/11/2007 typo spelling of Backpacker -->
<!-- 08.001 31/12/2007 50MHz & 70MHz UKAC are oneppq scoring added version number-->
<!-- 08.002 04/01/2008 removed 6 hour sections in 4m trophy contest -->
<!-- 08.003 16/01/2008 Changed name of 1.2/2.3Ghz UKAC to UHF UKAC -->
<!-- 08.004 07/03/2008 Added 2m backpackers as a contest series -->
<!-- 08.005 13/03/2008 Added LP section for the VHF championship.-->
<!-- 08.005 13/03/2008 Added special rules for VHF Championship-->
<!-- 08.006 16/05/2008 Added link to postcodes page-->
<!-- 08.007 17/06/2008 Changed 144 backpackers to individual contests-->
<!-- 08.008 17/06/2008 Added override flag for xmas contest -->
<!-- 09.001 23/06/2008 first version for 2009 -->
<!-- 09.002 03/08/2008 Changed REG1TEST freq for 23cms from 1,2 Ghz to 1,3 Ghz -->
<!-- 09.003 18/09/2008 Added icalurl and googleurl -->
<!-- 09.004 19/09/2008 changed the names of AO and AR UKAC sections -->
<!-- 09.005 07/10/2008 changed dates of 70cms AFS and 70MHz cumulatives -->
<!-- 09.006 07/11/2008 added new backpacker sections -->
<!-- 09.007 25/11/2008 added DXCC url-->
<!-- 09.008 08/12/2008 Changed AFS rules -->
<!-- 09.009 22/12/2008 removed old backpacker sections -->
<!-- 09.010 24/12/2008 Change to the registration words for MM section of NFD -->
<!-- 09.011 28/12/2008 Change Ghz to GHz and change Chirstmas cumulatives section to SF and O -->
<!-- 09.012 05/01/2009 removed the override flag for xmas so adding the Dec 70MHz UKAC -->
<!-- 09.013 24/02/2009 Changed the date of the 1st 50MHz contest and wording for normalised scores in S8-->
<calendar>
<version>09.013 24/02/2009</version>
<icalurl>http://www.google.com/calendar/ical/5cpj6pguhmkhg1otcsdmsvhtdg%40group.calendar.google.com/public/basic.ics</icalurl>
<googleurl>http://www.google.com/calendar/embed?src=5cpj6pguhmkhg1otcsdmsvhtdg%40group.calendar.google.com&amp;ctz=Europe/London</googleurl>
<notes_list>Calendar amended 05/01/09, Dec 70MHz UKAC added</notes_list>
<notes_list>Calendar amended 24/02/09, 1st 50MHz - date changed</notes_list>
<mult_type>
<name>M1</name>
<description>Post Codes and Countries</description>
<long_description>
Post Code and Country Multipliers. The multiplier for a band is the sum of the number of different DXCC countries and UK post code areas worked on that band.
A full list of DXCCs can be found here http://www.arrl.org/awards/dxcc/dxcclist.txt
A full list of Postcodes can be found here http://www.vhfcc.org/rules/09rules/postcode.htm
</long_description>
<exchange>first 2 letters of your Postcode</exchange>
<scoring_description> multiplied by the number of Countries plus Postcodes 
</scoring_description>
</mult_type>
<mult_type>
<name>M2</name>
<description>QTH Locators</description>
<long_description>
QTH Locator Multiplier. The multiplier for a band is the sum of the number of different large locator squares (e.g. JO01,IO91 etc.) worked on that band
</long_description>
<scoring_description> multiplied by the number of Locator Squares</scoring_description>
</mult_type>
<mult_type>
<name>M3</name>
<description>Post Codes, Countries and Locators</description>
<long_description>
Post Code, Country and QTH Locator Multiplier. The multiplier for a band is the sum of the number of different DXCC countries, U.K. post code areas, and large QTH locator squares (e.g. JO01,IO91 etc.) worked on that band.
A full list of DXCCs can be found here http://www.arrl.org/awards/dxcc/dxcclist.txt
A full list of Postcodes can be found here http://www.vhfcc.org/rules/09rules/postcode.htm
</long_description>
<exchange>first 2 letters of your Postcode</exchange>
<scoring_description> multiplied by the number of Countries plus Postcodes plus QTH locator squares</scoring_description>
</mult_type>
<mult_type>
<name>M4</name>
<description>Countries and Locators</description>
<long_description>
Country and QTH Locator Multiplier. The multiplier for a band is the sum of the number of different DXCC countries, and large QTH locator squares (e.g. JO01,IO91 etc.) worked on that band
A full list of DXCCs can be found here http://www.arrl.org/awards/dxcc/dxcclist.txt
</long_description>
<scoring_description> multiplied by the number of Countries plus QTH locator squares</scoring_description>
</mult_type>
<special_rule>
<name>S1</name>
<description>1 Point per QSO</description>
<long_description>
Instead of 1 point / km scoring (rule 5a), scores will be calculated at 1 point / QSO.
</long_description>
</special_rule>
<special_rule>
<name>S2</name>
<description>Deleted</description>
<long_description>
No longer used
</long_description>
</special_rule>
<special_rule>
<name>S3</name>
<description>Affiliated Societies contest </description>
<long_description>
This is an Affiliated Societies contest and is open to both individual entrants (who must be RSGB members), and to teams made up of a number of operators who must all be members of the same affiliated society, but not necessarily RSGB members themselves.

a. All members of the team must operate from within 50 miles of the normal meeting place of the society. No station may represent more than one society. No operator is allowed to use more than one callsign during the contest. In the case of national societies, each team must define a separate meeting place , and each team member must operate within 50 miles of that designated meeting place.

b. QSOs with other members of your team will count for points.

c. Each AFS member will be allocated to one or more teams in descending order of adjudicated score. For the purpose of calculating the overall AFS team score, each member of each team will be placed in one of 5 sections (3 for the 432MHz contest) Sections A, B, C etc. The highest placed member of each team will be placed in Section A, the second highest in Section B etc. All stations in each of the sections will have their score normalised against the highest score in that section, with the highest score gaining 1000 points. The final AFS team score will be the sum of the team members individual normalised scores.

d. Logs must be sent individually using the same Club Name. One log entry for each club should include a declaration in the soapbox/remarks that all operators are members of the Affiliated Society, and listing the QTH locator of the normal meeting place of the club.

</long_description>
</special_rule>
<special_rule>
<name>S4</name>
<description>Runs concurrently with a backpackers contest</description>
<long_description>
This contest runs concurrently with a backpackers contest. Stations entering the backpackers contest only may be worked once from a fixed location and once from their portable location for points.
</long_description>
</special_rule>
<special_rule>
<name>S5</name>
<description>Cumulative contest</description>
<long_description>
Scores will be normalised for each band/session as follows. 
Score for each band/session = (Score achieved x 1000) divded by (Band/session leader score).
For cumulative contests the overall score will normally be calculated from the best 3 normalised session scores 
It is impossible for you to determine your best sessions without knowing everyone else's scores, so please submit your logs and scores from all sessions in which you were active and allow the adjudicator to calculate your best sessions.

Stations may move location between individual cumulative activity periods
</long_description>
</special_rule>
<special_rule>
<name>S6</name>
<description>Runs concurrently with the first few hours of an RSGB 24 hour event</description>
<long_description>
This contest runs concurrently with the first few hours of an RSGB 24 hour event. You may submit entries to both contests with a single set of logs, but please include 2 cover sheets - one for the shorter contest and one for the 24 hour event. Entries may be automatically submitted into the 24 hour event unless you specifically request otherwise
</long_description>
</special_rule>
<special_rule>
<name>S7</name>
<description>Runs concurrently with all or part of an IARU co-ordinated contest</description>
<long_description>
This contest runs concurrently with all or part of an IARU co-ordinated contest. You may submit a single set of logs for entry to both the RSGB and IARU events. Entries will be submitted to the IARU event unless you specifically request otherwise but please note that electronic logs not in REG1TEST EDI format may be rejected  by the IARU adjudicators.
For IARU organised VHF/UHF contests, overseas stations are expected to enter via their own IARU society and the RSGB will not accept overseas entries for these contests.
</long_description>
</special_rule>
<special_rule>
<name>S8</name>
<description>Activity contest</description>
<long_description>
These contests are timed to co-incide with the last two hours of a number of European activity contests, with an extra half hour at the end to encourage intra UK activity.  They take place on Tuesdays from 2000-2230 local time with 144 MHz on the 1st Tuesday of the month, 432 MHz on the 2nd Tuesday, 1.3 GHz / 2.3 GHz on the 3rd Tuesday, 50 MHz on the 4th Tuesday, and 70 MHz where there is a 5th Tuesday in the month.

Please submit an entry after each session in which you are active. In order to speed adjudication entries will only be accepted by e-mail or web entry and must be sent within 10 days of the contest.

Scores will be normalised for each section in each session as follows. 
Score for each section/session = ((number of entrants+1)-(position of entrant))*1000/(number of entrants)
At the end of the year, on each band an overall score will be calculated from the best 8 normalised session scores.
It is impossible for you to determine your best sessions without knowing everyone else's scores, so please submit your logs and scores from all sessions in which you were active and allow the adjudicator to calculate your best sessions.

Stations may change section and move location between individual activity periods.

Certificates will be awarded to the overall winners and runners-up in each section and on each band in the same way as per the general rules. No certificates will be awarded for the individual events.
</long_description>
</special_rule>
<special_rule>
<name>S9</name>
<description>Club Championship</description>
<long_description>
a.        The individual entries by a club's members to the UK activity contests which take place on from 2000-2230 LOCAL time on each Tuesday in every month all count towards a society's overall score for the year for each UKAC. To maximise the club score, it's important for the club contest organiser to get as many members to come on for as many sessions as possible. A rolling club listing will be maintained on the Contest Committee web site www.vhfcc.org for each band.

b.        Stations enter the UKAC contests in the normal way, but need to include an AFS (affiliated society) name in the cover sheet of their entry. Entries to all sections of the UKAC count towards the overall club score which is the simple sum of the normalised scores of each team member operating that month. 

c.        Stations who enter on behalf of an affiliated society must be members of the affiliated society, but not necessarily RSGB members themselves.

d.        The G6NB Trophy will be awarded to the club with the highest score in the 2m UKAC at the end of the year. All 12 sessions will count towards the total club score.

</long_description>
</special_rule>
<special_rule>
<name>Backpacker</name>
<description>Special Backpackers Rules</description>
<long_description>
http://www.vhfcc.org/rules/09rules/BACKPACK.htm
</long_description>
</special_rule>
<special_rule>
<name>VHFNFD</name>
<description>Special Rules for VHF NFD</description>
<long_description>
http://www.vhfcc.org/rules/09rules/VHFNFD.htm
</long_description>
</special_rule>
<special_rule>
<name>VHF CHAMPIONSHIP</name>
<description>Special Rules for VHF Championship</description>
<long_description>
http://www.vhfcc.org/rules/09rules/championship.htm
</long_description>
</special_rule>
<special_rule>
<name>Low Power Contest</name>
<description>25W max. transmit o/p power,</description>
<long_description>
Maximum output Power 25W at the TX.
</long_description>
</special_rule>
<section>
<name>AO</name>
<description>UKAC Open </description>
<long_description> 
Maximum output power as permitted by standard licence conditions.
No antenna restrictions.
</long_description>
</section>
<section>
<name>AR</name>
<description>UKAC Restricted</description>
<long_description> 
The power output must not exceed 100W PEP at the transmitter.
Only one antenna may be used (i.e. no stacked, bayed or colinear arrays or switching between two or more antennas). A slot fed Yagi or Quad antenna is permitted. Dish or Backfire antennas must not exceed 2m diameter. 
</long_description>
<power>100</power>
<singleantenna>1</singleantenna>
</section>
<section>
<name>SF</name>
<description>Single Op Fixed</description>
<long_description> Stations must operate from permanent and substantial buildings located at the main station address as shown on the licence validation document. The spirit of the contest will be paramount.
</long_description>
</section>
<section>
<name>SO</name>
<description>Single Op Others</description>
<long_description> Single Operators not located at a fixed station address as defined in the SF section.
Stations not operating as a fixed station must use the /P callsign suffix. This does not preclude the use of /A or /M where appropriate.
</long_description>
</section>
<section>
<name>O</name>
<description>Open</description>
<long_description> This section is for portable stations and multi-operator fixed stations
Stations not operating as a fixed station must use the /P callsign suffix. Entrants may omit the /P suffix if using a special contest callsign, that is callsigns consisting of a single 'G' or 'M', a regional locator (if operating outside England) and a single suffix letter. This does not preclude the use of /A or /M where appropriate.
</long_description>
</section>
<section>
<name>A</name>
<description>All</description>
<long_description> This contest has a single section for all stations, single or multi-operator, fixed or portable in any combination
</long_description>
</section>
<section>
<name>6S</name>
<description>6 hours Single Op Fixed</description>
<long_description> Rules as per section "SF" except stations may choose any continuous 6 hour period in which to operate (e.g. 1500-2100, or 1917-0117). Alternatively you may split the 6 hour period into two segments separated by at least 1 hour off time. Serial numbers must start at 001 for this 6 hour period, and you cannot enter both this section and the full contest. In multi-band contests the same single 6 hour period must be used on all bands.
</long_description>
</section>
<section>
<name>6O</name>
<description>6 hours others</description>
<long_description> Rules as per section "O" except stations may choose any continuous 6 hour period in which to operate (e.g. 1500-2100, or 1917-0117). Alternatively you may split the 6 hour period into two segments separated by at least 1 hour off time. Serial numbers must start at 001 for this 6 hour period, and you cannot enter both this section and the full contest. In multi-band contests the same single 6 hour period must be used on all bands.
</long_description>
</section>
<section>
<name>3B</name>
<description>3W Backpacker</description>
<long_description> 
a) Duration: 4 hours.  See Contest Calendar for individual session dates and start time 
b) Mode: All Mode 
c) 3W maximum output from the transmitter 
d) Single antenna with no more than 20 half-wave elements (or equivalent)
e) Antenna height: Driven element no more than 4m above the ground
f) No operation from a motor vehicle. The vehicle supply must not be used to power any equipment used during the contest or to recharge batteries for the equipment.
g) All equipment used during the contest must be battery, wind or solar powered.
h) Equipment must be carried and operated at least 100m from the transportation vehicle. 
</long_description>
<power>3</power>
<height>4</height>
</section>
<section>
<name>10H</name>
<description>10W Hill Toppers</description>
<long_description> 
a) Duration: 4 hours.  See Contest Calendar for individual session dates and start time
b) Mode: All Mode
c) 10W maximum output from the transmitter.
d) One or more antennas with no more than 20 half-wave elements (or equivalent) in total.
e) Antenna height: Driven element no more than 6m above the ground
f) Operation from a motor vehicle permitted.  
g) All equipment used during the contest must be battery, wind or solar powered.  If equipment is powered from a vehicle supply, the engine must be switched off for the duration of the contest.
</long_description>
<power>10</power>
<height>6</height>
</section>
<section>
<name>Open</name>
<description>Open section of VHF NFD</description>
<long_description>
(i) Maximum output power as permitted by standard licence conditions.

(ii) General rules apply

(iii) Operate on any bands from the following list, but only the best 4 normalised scores will count to the final total:

50MHz (6m) 1400 to 2200 Saturday (all mode)

70MHz (4m) 0800 to 1400 Sunday (all mode)

144MHz (2m) 1400 Saturday to 1400 Sunday (all mode)

432MHz (70cm) 1400 Saturday to 1400 Sunday (all mode)

1.3GHz (23cm) 1400 Saturday to 1400 Sunday (all mode)
</long_description>
</section>
<section>
<name>R</name>
<description>Restricted Section of VHF NFD</description>
<long_description>
(i) The power output of any band must not exceed 100W PEP at the transmitter.

(ii) The height of any part of the antenna's driven element must not exceed 10 metres above ground level.

(iii) Only one antenna per band may be used (i.e. no stacked, bayed or colinear arrays or switching between two or more antennas). A slot fed Yagi or Quad antenna is permitted. Dish or Backfire antennas must not exceed 2m diameter.

(iv) Operate on up to 4 bands from the following list:

50MHz (6m) 1400 to 2200 Saturday (all mode)

70MHz (4m) 0800 to 1400 Sunday (all mode)

144MHz (2m) 1400 Saturday to 1400 Sunday (all mode)

432MHz (70cm) 1400 Saturday to 1400 Sunday (all mode)

1.3GHz (23cm) 1400 Saturday to 1400 Sunday (all mode)
</long_description>
<power>100</power>
<height>10</height>
<singleantenna>1</singleantenna>
</section>
<section>
<name>L</name>
<description>Low Power Section of VHF NFD</description>
<long_description>
(i) The power output of any band must not exceed 25W PEP at the transmitter.

(ii) The height of any part of the antenna's driven element must not exceed 10 metres above ground level.

(iii) Only one antenna per band may be used (i.e. no stacked, bayed or colinear arrays or switching between two or more antennas). A slot fed Yagi or Quad antenna is permitted. Dish or Backfire antennas must not exceed 2m diameter.

(iv) Operate on up to 3 bands from the following list:

50MHz (6m) 1400 to 2200 Saturday (all mode)

70MHz (4m) 0800 to 1400 Sunday (all mode)

144MHz (2m) 1400 Saturday to 1400 Sunday (all mode)

432MHz (70cm) 1400 Saturday to 1400 Sunday (all mode)

1.3GHz (23cm) 1400 Saturday to 1400 Sunday (all mode)

(v) Each band may be operated for no more than 16 hours (except for 6m and 4m: see 7.3 (iv) above) during the contest period. Each rest period must last at least 1 hour.
</long_description>
<power>25</power>
<height>10</height>
<singleantenna>1</singleantenna>
</section>
<section>
<name>M</name>
<description>Mix and Match Section of VHF NFD</description>
<long_description>
7.4 Mix and Match (M)

(i) A group can elect to place different bands into Restricted, Low-Power or Open sections. E.g. 4m in Restricted, 2m and 70cm in Open, and 23cm in Low Power. This decision must be made at registration time. At least one station must be in a different section to the other stations (e.g. 6m, 4m and 2m in the Open section, 70cm in the Restricted section)

(ii) Individual band entry will be tabulated in the appropriate main section, and a normalised score for the band produced on this basis.

(iii) The sum of the normalised scores will appear in a separate Mix and Match section table.

(iv) Operate on up to 4 bands from the following list:

50MHz (6m) 1400 to 2200 Saturday (all mode)

70MHz (4m) 0800 to 1400 Sunday (all mode)

144MHz (2m) 1400 Saturday to 1400 Sunday (all mode)

432MHz (70cm) 1400 Saturday to 1400 Sunday (all mode)

1.3GHz (23cm) 1400 Saturday to 1400 Sunday (all mode)

(v) Note that 2m, 70cm or 23cm stations entered in the Low Power section may be operated for no more than 16 hours during the contest period. Each rest period must last at least 1 hour.
</long_description>
<overall_section>yes</overall_section>
</section>
<section>
<name>LP</name>
<description>Single Operator, Fixed, 25W - Single Antenna</description>
<long_description>
This section is open to single operator fixed stations using 25W or less output and a single antenna. 
When applied to the VHF Championship, if a station enters some contests with high power or extra antennas, and some with low power and a single antenna, only the low power, single antenna scores will count towards the championship.
</long_description>
<power>25</power>
<singleantenna>1</singleantenna>
</section>
<band>
<name>50NFD</name>
<reg1band>50 MHz</reg1band>
<wavelength>6</wavelength>
  <time_list>
    <month_list>Jul</month_list>
    <start_day>6</start_day>
    <start_week>1</start_week>
    <start_time>1400</start_time>
    <time_type>GMT</time_type>
    <duration>8</duration>
  </time_list>
</band>
<band>
<name>50</name>
<reg1band>50 MHz</reg1band>
<wavelength>6</wavelength>
</band>
<band>
<name>70NFD</name>
<reg1band>70 MHz</reg1band>
<wavelength>4</wavelength>
  <time_list>
    <month_list>Jul</month_list>
    <start_day>7</start_day>
    <start_week>1</start_week>
    <start_time>0800</start_time>
    <time_type>GMT</time_type>
    <duration>6</duration>
  </time_list>
</band>
<band>
<name>70</name>
<reg1band>70 MHz</reg1band>
<wavelength>4</wavelength>
</band>
<band>
<name>144</name>
<reg1band>145 MHz</reg1band>
<wavelength>2</wavelength>
</band>
<band>
<name>432</name>
<reg1band>435 MHz</reg1band>
<wavelength>70cms</wavelength>
</band>
<band>
<name>1296</name>
<reg1band>1,2 GHz</reg1band>
<wavelength>23cms</wavelength>
</band>
<band>
<name>2320</name>
<reg1band>2,3 GHz</reg1band>
<wavelength>13cms</wavelength>
</band>
<band>
<name>3400</name>
<reg1band>3,4 GHz</reg1band>
<wavelength>9cms</wavelength>
</band>
<band>
<name>5760</name>
<reg1band>5,7 GHz</reg1band>
<wavelength>6cms</wavelength>
</band>
<band>
<name>10368</name>
<reg1band>10 GHz</reg1band>
<wavelength>3cms</wavelength>
</band>
<band>
<name>24GHz</name>
<reg1band>24 GHz</reg1band>
<wavelength>12mm</wavelength>
</band>
<band>
<name>47GHz</name>
<reg1band>47 GHz</reg1band>
<wavelength>6mm</wavelength>
</band>
<band>
<name>76GHz</name>
<reg1band>76 GHz</reg1band>
<wavelength>4mm</wavelength>
</band>
<band>
<name>120GHz</name>
<reg1band>120 GHz</reg1band>
<wavelength>2.5mm</wavelength>
</band>
<band>
<name>144GHz</name>
<reg1band>144 GHz</reg1band>
<wavelength>2mm</wavelength>
</band>
<band>
<name>248GHz</name>
<reg1band>248 GHz</reg1band>
<wavelength>1.2mm</wavelength>
</band>
<contest_series>
<name>vhfchampionship</name>
<description>VHF Championship</description>
<contest_list>mar144432</contest_list>
<contest_list>70cmstrophy</contest_list>
<contest_list>may144</contest_list>
<contest_list>50trophy</contest_list>
<contest_list>lp144</contest_list>
<contest_list>lp432</contest_list>
<contest_list>70trophy</contest_list>
<contest_list>144trophy</contest_list>
<contest_list>uhftrophy</contest_list>
<section_list>SF</section_list>
<section_list>O</section_list>
<section_list>LP</section_list>
<special_rules_list>VHF CHAMPIONSHIP</special_rules_list>
<award_list>Racal Radio Cup is awarded to the overall winner of the Open Section</award_list>
<award_list>John Pilags Memorial Trophy is awarded to the Leading Single Operator Fixed Station</award_list>
<award_list>Low Power VHF Championship Trophy is awarded to the 25W or less Single antenna, Single Operator, Fixed Station </award_list>
</contest_series>
<contest_series>
<name>144backpackchamp</name>
<description>144MHz Backpackers Championship</description>
<contest_list>144backpack</contest_list>
<special_rules_list>Backpacker</special_rules_list>
<award_list>Backpackers Trophy is awarded to the overall winner</award_list>
</contest_series>
<contest>
  <name>4mcumulatives</name>
  <description>70MHz Cumulatives #</description>
  <short_description>70MHz Cumulatives</short_description>
  <time_list>
    <month_list>Jan</month_list>
    <month_list>Feb</month_list>
    <month_list>Mar</month_list>
    <start_day>6+1</start_day>
    <start_week>2</start_week>
    <start_time>1000</start_time>
    <time_type>GMT</time_type>
    <duration>2</duration>
  </time_list>
  <time_list>
    <month_list>Jan</month_list>
    <month_list>Feb</month_list>
    <start_day>7</start_day>
    <start_week>4</start_week>
    <start_time>1000</start_time>
    <time_type>GMT</time_type>
    <duration>2</duration>
  </time_list>
  <section_list>O</section_list>
  <section_list>SF</section_list>
  <scoring>
    <perkms>1</perkms>
  </scoring>
  <special_rules_list>S5</special_rules_list>
  <band_list>70</band_list>
  <entry_date>16 days after the last activity period</entry_date>
</contest>
<contest>
  <name>afs432MHz</name>
  <description>432MHz Affiliated Societies Contest</description>
  <short_description>432MHz AFS</short_description>
  <time_list>
    <month_list>Feb</month_list>
    <start_day>6+1</start_day>
    <start_week>1</start_week>
    <start_time>0900</start_time>
    <time_type>GMT</time_type>
    <duration>4</duration>
  </time_list>
  <section_list>O</section_list>
  <section_list>SF</section_list>
  <scoring>
    <perkms>1</perkms>
  </scoring>
  <special_rules_list>S3</special_rules_list>
  <band_list>432</band_list>
<award_list>The G0ODQ Trophy will awarded to the winning AFS entry</award_list>
<entry_date>16 days</entry_date>
</contest>
<contest>
  <name>1st70MHz</name>
  <description>First 70MHz Contest</description>
  <time_list>
    <month_list>Apr</month_list>
    <start_day>7</start_day>
    <start_week>1</start_week>
    <start_time>0900</start_time>
    <time_type>GMT</time_type>
    <duration>3</duration>
  </time_list>
  <section_list>O</section_list>
  <section_list>SF</section_list>
  <scoring>
    <perkms>1</perkms>
  </scoring>
  <band_list>70</band_list>
<entry_date>16 days</entry_date>
</contest>
<contest>
  <name>2nd70MHz</name>
  <description>Second 70MHz Contest</description>
  <time_list>
    <month_list>Sep</month_list>
    <start_day>7</start_day>
    <start_week>2</start_week>
    <start_time>0900</start_time>
    <time_type>GMT</time_type>
    <duration>3</duration>
  </time_list>
  <section_list>O</section_list>
  <section_list>SF</section_list>
  <scoring>
    <perkms>1</perkms>
  </scoring>
  <band_list>70</band_list>
<entry_date>16 days</entry_date>
</contest>
<contest>
  <name>1st50MHz</name>
  <description>First 50MHz Contest</description>
  <time_list>
    <month_list>Apr</month_list>
    <start_day>6+1</start_day>
    <start_week>2</start_week>
    <start_time>0900</start_time>
    <time_type>GMT</time_type>
    <duration>3</duration>
  </time_list>
  <section_list>O</section_list>
  <section_list>SF</section_list>
  <scoring>
    <perkms>1</perkms>
  </scoring>
  <band_list>50</band_list>
  <mult>M3</mult>
<entry_date>16 days</entry_date>
</contest>
<contest>
  <name>mayuhf</name>
  <description>432MHz-248GHz Contest</description>