<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calendar [
<!ELEMENT calendar (version, icalurl?, googleurl?, notes_list*,  mult_type+, ColumnFormat+, resultsFormatType*, special_rule+, section+, band+, contest_series+, seriesCollate+, seriesResult+, contest+)>
<!ELEMENT mult_type (name, description, long_description, exchange?, scoring_description?)>
<!ELEMENT ColumnFormat (name, Columns+ )>
<!ELEMENT Columns EMPTY>
<!ATTLIST Columns Index CDATA #IMPLIED>
<!ATTLIST Columns Title CDATA #REQUIRED>
<!ATTLIST Columns Nocolumn CDATA #IMPLIED>
<!ATTLIST Columns Merge CDATA #IMPLIED>
<!ATTLIST Columns Field CDATA #REQUIRED>
<!ATTLIST Columns img CDATA #IMPLIED>
<!ATTLIST Columns Align CDATA #IMPLIED>
<!ATTLIST Columns Sections CDATA #IMPLIED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT long_description (#PCDATA)>
<!ELEMENT resdescription (#PCDATA)>
<!ELEMENT band_list (#PCDATA)>
<!ELEMENT special_rule (name, description, long_description)>
<!ELEMENT resultsFormatType (name, ColumnFormatUsed, TeamSize?, cumulativeField?, normType?, useContestID?, ScoresCount?)>
<!ELEMENT section (name, description, resdescription?, long_description, power?, height?, singleantenna?, overall_section?, month_list*, collate?,certfields?)>
<!ELEMENT contest (name, description, short_description?, time_list*, section_list+, scoring, special_rules_list*, band_list+, mult?, mode?, iaru?, power?, award_list*, entry_date, override?, club_contest?, resultsFormatUsed?)>
<!ELEMENT time_list (month_list+, ((start_day, start_week) | start_date_list+), start_time, time_type, duration, mult?)>
<!ELEMENT contest_series (name, description, contest_list+, section_list*, special_rules_list*, award_list*)>
<!ELEMENT seriesResult (name,ctl?,ScoresCount?,id_list+)>
<!ELEMENT id_list (name,id,resultName,year,normaliseby?,collate_type?,collate_list*)>
<!ELEMENT seriesCollate (name,collate_list+)>
<!ELEMENT collate_list (name,field,display?,filter,scorefield,table)>
<!ELEMENT resultName (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT certfields (#PCDATA)>
<!ELEMENT ctl (#PCDATA)>
<!ELEMENT collate_type (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT normaliseby (#PCDATA)>
<!ELEMENT field (#PCDATA)>
<!ELEMENT display (#PCDATA)>
<!ELEMENT scorefield (#PCDATA)>
<!ELEMENT filter (#PCDATA)>
<!ELEMENT table (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT month_list (#PCDATA)>
<!ELEMENT collate (#PCDATA)>
<!ELEMENT start_day (#PCDATA)>
<!ELEMENT start_week (#PCDATA)>
<!ELEMENT start_time (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT section_list (#PCDATA)>
<!ELEMENT scoring ((perkms) | (oneppq))>
<!ELEMENT scoring_description (#PCDATA)>
<!ELEMENT perkms (#PCDATA)>
<!ELEMENT special_rules_list (#PCDATA)>
<!ELEMENT reg1band (#PCDATA)>
<!ELEMENT band (name,  reg1band, wavelength, time_list?, multfactor?)>
<!ELEMENT freq (#PCDATA)>
<!ELEMENT power (#PCDATA)>
<!ELEMENT wavelength (#PCDATA)>
<!ELEMENT multfactor (#PCDATA)>
<!ELEMENT iaru (#PCDATA)>
<!ELEMENT mult (#PCDATA)>
<!ELEMENT mode (#PCDATA)>
<!ELEMENT contest_list (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT singleantenna (#PCDATA)>
<!ELEMENT exchange (#PCDATA)>
<!ELEMENT championship (#PCDATA)>
<!ELEMENT time_type (#PCDATA)>
<!ELEMENT oneppq (#PCDATA)>
<!ELEMENT award_list (#PCDATA)>
<!ELEMENT override (#PCDATA)>
<!ELEMENT entry_date (#PCDATA)>
<!ELEMENT ColumnFormatUsed (#PCDATA)>
<!ELEMENT resultsFormatUsed (#PCDATA)>
<!ELEMENT cumulativeField (#PCDATA)>
<!ELEMENT TeamSize (#PCDATA)>
<!ELEMENT normType (#PCDATA)>
<!ELEMENT useContestID (#PCDATA)>
<!ELEMENT ScoresCount (#PCDATA)>
<!ELEMENT start_date_list (#PCDATA)>
<!ELEMENT short_description (#PCDATA)>
<!ELEMENT overall_section (#PCDATA)>
<!ELEMENT icalurl (#PCDATA)>
<!ELEMENT googleurl (#PCDATA)>
<!ELEMENT notes_list (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT club_contest (#PCDATA)>
]>
<!-- RSGB VHF contest calendar and rules by G4CLA-->
<!-- 12.038 04/09/12 G4CLA - create 144MHz backpacker series results plus clean up-->
<!-- 12.039 05/09/12 G4CLA - add ctl names for contest series results-->
<!-- 12.040 06/09/12 G4CLA - add ScoresCount for shfukac -->
<!-- 12.041 06/09/12 G4CLA - add ScoresCount for backpackers series  -->
<!-- 12.042 13/09/12 G4CLA - add certfields for VHF NFD sections  -->
<!-- 12.043 14/09/12 G4CLA - add added autocerts for VHF NFD -->
<!-- 12.044 17/09/12 G4CLA - add added autocerts for 4m cumulatives and whichields for O and SF section -->
<!-- 12.045 04/10/12 G4CLA - removed dec dates for 6m and shf ukacs-->
<!-- 12.046 11/10/12 G4CLA - changed long description for VHF CHAMPIONSHIP removed newlines-->
<!-- 12.047 15/10/12 G4CLA - donwloadable certs for May 144MHz contest and associated sections-->
<!-- 12.048 21/10/12 G4CLA - added clubdistance tag -->
<!-- 12.049 22/10/12 G4CLA - added output formats for low power contests -->
<!-- 12.050 31/10/12 G4CLA - added output formats for 2m trophy -->
<!-- 12.051 01/11/12 G4CLA - changed results format and added auto_certs for 50MHz AFS-->
<!-- 12.052 05/11/12 G4CLA - Auto certs for low power contests-->
<!-- 12.053 15/11/12 G4CLA - Auto certs for 4m UKAC and cert info for UKAC sections-->
<!-- 12.054 19/11/12 G4CLA - added HF contest club calls to superleague-->
<!-- 12.055 28/11/12 G4CLA - added operators to backpackers results-->
<!-- 12.056 10/12/12 G4CLA - added xmas results format and contest series-->
<!-- 12.057 12/12/12 G4CLA - added marconi CW results format -->
<!-- 12.058 12/12/12 G4CLA - added Oct UHF results format -->
<!-- 12.059 13/12/12 G4CLA - added 23cms and 13cms trophy results format -->
<!-- 12.060 13/12/12 G4CLA - added individual results for the overall UKACs-->
<!-- 13.001 05/11/12 G4CLA - added M6. Changed duration of 70cms and 2m afs contests-->
<!-- 13.002 13/12/12 G4CLA - add ical and google calendar-->
<!-- 13.003 10/12/12 G4CLA - Change in method of calculating UKAC final scores. changed .htl links to .shtml-->
<!-- 13.004 17/12/12 G4CLA - Change from 2012 cvalendar -->
<!-- 13.005 29/12/12 G4CLA - Change from 2012 cvalendar -->
<!-- 13.006 02/01/13 G4CLA - Added VHF CW series results-->
<!-- 13.007 04/01/13 G4CLA - Added certs for sections 3B and 10H-->
<!-- 13.008 07/01/13 G4CLA - moved 2nd 70MHz contests one week forward-->
<!-- 13.009 20/01/13 G4CLA - added cw champs and more auto_certs-->
<!-- 13.010 21/01/13 G4CLA - added 80m AFS contests and 70cms AFS to superleaue series result-->
<!-- 13.011 22/01/13 G4CLA - changed names for 2m and 70cms AFS contests . They had short descriptions so should be ok in alerts-->
<!-- 13.012 30/01/13 G4CLA - Add MS section of VHF NFD-->
<!-- 13.013 18/02/13 G4CLA - changed wording of maximum number os sessions that count in UKACs-->
<!-- 13.014 22/02/13 G4CLA - removed the <club_contest>no</clubcontest> from 4m and xmas cumulatives and added to May and Oct UHF contests-->
<!-- 13.015 22/02/13 G4CLA - removed Dec 70MHz UKAC -->
<!-- 13.016 18/03/13 G4CLA - add stats format for afs-->
<!-- 13.017 18/03/13 G4CLA - had to put <club_contest>no</clubcontest> back for 4m culumatives lese results dont work-->
<!-- 13.018 24/04/13 G4CLA - increase duration of 6m afs to 4 hours-->
<!-- 13.018 29/04/13 G4CLA - Remove VHF CW chamop from individual contests, add highlight color for contest series -->
<!-- 13.019 08/06/13 G4CLA - Collation of overall SHF UKAC Scores was wrong should sued date=0 !-->
<!-- 13.020 02/08/13 G4CLA - always collate open section of VHF Champs on clubname !-->
<!-- 13.021 14/08/13 G4CLA - only include UK stations in stndard VHF champs -->
<!-- 13.022 15/08/13 G4CLA - added VHF NFD MS Section to results and centenary points and sweepers sections -->
<calendar>
<version>13.022 15/08/2013</version>
<icalurl>http://www.rsgbcc.org/icals/2013vhf.ics</icalurl>
<googleurl>https://www.google.com/calendar/embed?src=2puobjml9pkpdvavmj0hf8ac1g%40group.calendar.google.com&amp;ctz=Europe/London</googleurl>
<notes_list>05/11/12: Changed duration and start time of 2m and 70cms AFS contests</notes_list>
<notes_list>07/01/13: Move date of 2nd 70MHz contest forward one week</notes_list>
<notes_list>28/02/13: Removed the December 70MHz UKAC </notes_list>
<notes_list>24/04/13: Increase duration of 50MHz AFS to 4 hours </notes_list>
<mult_type>
<name>M1</name>
<description>Post Codes and Countries</description>
<long_description>
Post Code and Country Multipliers. The multiplier for a band is the sum of the number of different DXCC countries and UK post code areas worked on that band.
Contacts with stations where the country cannot be determined (such as those with GB stations), will not count as a country multiplier, even if the country the station was operated from is self-evident.
A full list of DXCCs can be found here http://www.arrl.org/files/file/DXCC/dxcclist_2011e.txt
A full list of Postcodes can be found here http://www.rsgbcc.org/vhf/rules/13rules/postcode.shtml
</long_description>
<exchange> serial number and QTH Locator and UK stations send the first 2 letters of their Postcode</exchange>
<scoring_description> multiplied by the number of Countries plus Postcodes 
</scoring_description>
</mult_type>
<mult_type>
<name>M2</name>
<description>QTH Locators</description>
<long_description>
QTH Locator Multiplier. The multiplier for a band is the sum of the number of different large locator squares (e.g. JO01,IO91 etc.) worked on that band
</long_description>
<exchange> serial number and QTH Locator</exchange>
<scoring_description> multiplied by the number of Locator Squares</scoring_description>
</mult_type>
<mult_type>
<name>M3</name>
<description>Post Codes, Countries and Locators</description>
<long_description>
Post Code, Country and QTH Locator Multiplier. The multiplier for a band is the sum of the number of different DXCC countries, U.K. post code areas, and large QTH locator squares (e.g. JO01,IO91 etc.) worked on that band.
Contacts with stations where the country cannot be determined (such as those with GB stations), will not count as a country multiplier, even if the country the station was operated from is self-evident.
A full list of DXCCs can be found here http://www.arrl.org/files/file/DXCC/dxcclist_2011e.txt
A full list of Postcodes can be found here http://www.rsgbcc.org/vhf/rules/13rules/postcode.shtml
</long_description>
<exchange> serial number and QTH Locator and UK stations send the first 2 letters of their Postcode</exchange>
<scoring_description> multiplied by the number of Countries plus Postcodes plus QTH locator squares</scoring_description>
</mult_type>
<mult_type>
<name>M4</name>
<description>Countries and Locators</description>
<long_description>
Country and QTH Locator Multiplier. The multiplier for a band is the sum of the number of different DXCC countries, and large QTH locator squares (e.g. JO01,IO91 etc.) worked on that band
Contacts with stations where the country cannot be determined (such as those with GB stations), will not count as a country multiplier, even if the country the station was operated from is self-evident.
A full list of DXCCs can be found here http://www.arrl.org/files/file/DXCC/dxcclist_2011e.txt
</long_description>
<exchange> serial number and QTH Locator</exchange>
<scoring_description> multiplied by the number of Countries plus QTH locator squares</scoring_description>
</mult_type>
<mult_type>
<name>M5</name>
<description>UK QTH Locators</description>
<long_description>
UK QTH Locator Multipliers. The multiplier is the sum of the number of different large locator squares (e.g. JO01,IO91 etc.) worked on that band. Only contacts with UK stations (G, GW, GM, GI, GD, GU, GJ) count for multipliers.
</long_description>
<exchange> serial number and QTH Locator</exchange>
<scoring_description> multiplied by the number of UK Locator Squares</scoring_description>
</mult_type>
<mult_type>
<name>M6</name>
<description>UK Locators plus non-UK Countries</description>
<long_description>
UK QTH Locators plus non-UK countries. The multiplier is the sum of the number of different large UK locator squares (e.g. JO01,IO91 etc.) plus the total number of non-UK countries worked on that band.
</long_description>
<exchange> serial number and QTH Locator</exchange>
<scoring_description> multiplied by the sum of UK Locator Squares and non-UK countries</scoring_description>
</mult_type>
<ColumnFormat>
        <name>xmasresults</name>
        <Columns Title = "Certificate Winner" Nocolumn="true" Merge="right" Field="cert" img="cert.gif" ></Columns>
        <Columns Title = "Pos___" Field="position" Merge="left" Align="right" ></Columns>
        <Columns Index="true" Title = "Callsign" Field ="call" Align = "left" ></Columns>
        <Columns Title = "Loc" Field ="locator" Align = "center" ></Columns>
        <Columns Title = "QSOS" Field = "Qs" Align = "right" ></Columns>
        <Columns Title = "Mults" Field="mults" Align = "right" ></Columns>
        <Columns Title = "Total" Field="totalScore" Align = "right" ></Columns>
        <Columns Title = "Norm" Field="normalisedScore" Align = "right" ></Columns>
        <Columns Title = "ODX" Field="ODXCall" Align = "center" ></Columns>
        <Columns Title = "Kms" Field="ODXKms" Align = "center" ></Columns>
        <Columns Title = "Power" Field="power" Align = "center" ></Columns>
        <Columns Title = "Ant" Field="ant" Align = "center" ></Columns>
        <Columns Title = "Equipment" Field="equipment" Align = "center" img="tx.gif" ></Columns>
        <Columns Title = "Comments" Field="SoapBox" Align = "left" img="soapbox.gif" ></Columns>
</ColumnFormat>
<ColumnFormat>
        <name>vhfmultsandnorm</name>
        <Columns Title = "Certificate Winner" Nocolumn="true" Merge="right" Field="cert" img="cert.gif" ></Columns>
        <Columns Title = "Pos___" Field="position" Merge="left" Align="right" ></Columns>
        <Columns Index="true" Title = "Callsign" Field ="call" Align = "left" ></Columns>
        <Columns Title = "Loc" Field ="locator" Align = "center" ></Columns>
        <Columns Title = "QSOS" Field = "Qs" Align = "right" ></Columns>
        <Columns Title = "Score" Field="score" Align = "right" ></Columns>
        <Columns Title = "Mults" Field="mults" Align = "right" ></Columns>
        <Columns Title = "Total" Field="totalScore" Align = "right" ></Columns>
        <Columns Title = "Norm" Field="normalisedScore" Align = "right" ></Columns>
        <Columns Title = "ODX" Field="ODXCall" Align = "center" ></Columns>
        <Columns Title = "Kms" Field="ODXKms" Align = "center" ></Columns>
        <Columns Title = "Power" Field="power" Align = "center" ></Columns>
        <Columns Title = "Group" Field="clubName" Align = "center" ></Columns>
        <Columns Title = "Ant" Field="ant" Align = "center" img="tower.gif" ></Columns>
        <Columns Title = "Equipment" Field="equipment" Align = "center" img="tx.gif" ></Columns>
        <Columns Title = "Comments" Field="SoapBox" Align = "left" img="soapbox.gif" ></Columns>
</ColumnFormat>
<ColumnFormat>
        <name>vhfnorm</name>
        <Columns Title = "Certificate Winner" Nocolumn="true" Merge="right" Field="cert" img="cert.gif" ></Columns>
        <Columns Title = "Pos___" Field="position" Merge="left" Align="right" ></Columns>
        <Columns Title = "Group" Field="clubName" Align = "center" Sections= "O,6O" ></Columns>
        <Columns Index="true" Title = "Callsign" Field ="call" Align = "left" ></Columns>
        <Columns Title = "Loc" Field ="locator" Align = "center" ></Columns>
        <Columns Title = "QSOS" Field = "Qs" Align = "right" ></Columns>
        <Columns Title = "Score" Field="score" Align = "right" ></Columns>
        <Columns Title = "Norm" Field="normalisedScore" Align = "right" ></Columns>
        <Columns Title = "ODX" Field="ODXCall" Align = "center" ></Columns>
        <Columns Title = "Kms" Field="ODXKms" Align = "center" ></Columns>
        <Columns Title = "Power" Field="power" Align = "center" ></Columns>
        <Columns Title = "Ant" Field="ant" Align = "center" img="tower.gif" ></Columns>
        <Columns Title = "Equipment" Field="equipment" Align = "center" img="tx.gif" ></Columns>
        <Columns Title = "Comments" Field="SoapBox" Align = "left" img="soapbox.gif" ></Columns>
        <Columns Title = "Operators" Field="Operators" Align = "left" Sections= "O,6O" ></Columns>
</ColumnFormat>
<ColumnFormat>
        <name>vhfgroup</name>
        <Columns Title = "Certificate Winner" Nocolumn="true" Merge="right" Field="cert" img="cert.gif" ></Columns>
        <Columns Title = "Pos___" Field="position" Merge="left" Align="right" ></Columns>
        <Columns Title = "Group" Field="clubName" Align = "center" Sections= "O,6O" ></Columns>
        <Columns Index="true" Title = "Callsign" Field ="call" Align = "left" ></Columns>
        <Columns Title = "Loc" Field ="locator" Align = "center" ></Columns>
        <Columns Title = "QSOS" Field = "Qs" Align = "right" ></Columns>
        <Columns Title = "Score" Field="score" Align = "right" ></Columns>
        <Columns Title = "ODX" Field="ODXCall" Align = "center" ></Columns>
        <Columns Title = "Kms" Field="ODXKms" Align = "center" ></Columns>
        <Columns Title = "Power" Field="power" Align = "center" ></Columns>
        <Columns Title = "Ant" Field="ant" Align = "center" img="tower.gif" ></Columns>
        <Columns Title = "Equipment" Field="equipment" Align = "center" img="tx.gif" ></Columns>
        <Columns Title = "Comments" Field="SoapBox" Align = "left" img="soapbox.gif" ></Columns>
        <Columns Title = "Operators" Field="Operators" Align = "left" Sections= "O,6O" ></Columns>
</ColumnFormat>
<ColumnFormat>
        <name>vhfnfd</name>
        <Columns Title = "Certificate Winner" Nocolumn="true" Merge="right" Field="cert" img="cert.gif" ></Columns>
        <Columns Title = "Pos___" Field="position" Merge="left" Align="right" ></Columns>
        <Columns Title = "Group" Field="clubName" Align = "center" Sections= "Open,R,L,MS" ></Columns>
        <Columns Index="true" Title = "Callsign" Field ="call" Align = "left" ></Columns>
        <Columns Title = "Loc" Field ="locator" Align = "center" ></Columns>
        <Columns Title = "QSOS" Field = "Qs" Align = "right" ></Columns>
        <Columns Title = "Score" Field="score" Align = "right" ></Columns>
        <Columns Title = "Norm" Field="normalisedScore" Align = "right" Sections= "Open,R,L,MS"></Columns>
        <Columns Title = "Mults" Field="mults" Align = "right" Sections= "FSO,FSR" ></Columns>
        <Columns Title = "Total" Field="totalScore" Align = "right" Sections= "FSO,FSR" ></Columns>
        <Columns Title = "Centenary Points" Field="total2" Align = "center" ></Columns>
        <Columns Title = "ODX" Field="ODXCall" Align = "center" ></Columns>
        <Columns Title = "Kms" Field="ODXKms" Align = "center" ></Columns>
        <Columns Title = "Power" Field="power" Align = "center" ></Columns>
        <Columns Title = "Ant" Field="ant" Align = "center" img="tower.gif" ></Columns>
        <Columns Title = "Equipment" Field="equipment" Align = "center" img="tx.gif" ></Columns>
        <Columns Title = "Comments" Field="SoapBox" Align = "left" img="soapbox.gif" ></Columns>
        <Columns Title = "Operators" Field="Operators" Align = "left" Sections= "Open,R,L,MS"  ></Columns>
</ColumnFormat>
<ColumnFormat>
        <name>vhfmults</name>
        <Columns Title = "Certificate Winner" Nocolumn="true" Merge="right" Field="cert" img="cert.gif" ></Columns>
        <Columns Title = "Pos___" Field="position" Merge="left" Align="right" ></Columns>
        <Columns Title = "Group" Field="clubName" Align = "center" Sections= "O,6O,A" ></Columns>
        <Columns Index="true" Title = "Callsign" Field ="call" Align = "left" ></Columns>
        <Columns Title = "Loc" Field ="locator" Align = "center" ></Columns>
        <Columns Title = "QSOS" Field = "Qs" Align = "right" ></Columns>
        <Columns Title = "Score" Field="score" Align = "right" ></Columns>
        <Columns Title = "Mults" Field="mults" Align = "right" ></Columns>
        <Columns Title = "Total" Field="totalScore" Align = "right" ></Columns>
        <Columns Title = "ODX" Field="ODXCall" Align = "center" ></Columns>
        <Columns Title = "Kms" Field="ODXKms" Align = "center" ></Columns>
        <Columns Title = "Power" Field="power" Align = "center" ></Columns>
        <Columns Title = "Ant" Field="ant" Align = "center" img="tower.gif" ></Columns>
        <Columns Title = "Equipment" Field="equipment" Align = "center" img="tx.gif" ></Columns>
        <Columns Title = "Comments" Field="SoapBox" Align = "left" img="soapbox.gif" ></Columns>
        <Columns Title = "Operators" Field="Operators" Align = "left" Sections= "O,6O,A,3B,10H" ></Columns>
</ColumnFormat>
<ColumnFormat>
        <name>vhf</name>
        <Columns Title = "Certificate Winner" Nocolumn="true" Merge="right" Field="cert" img="cert.gif" ></Columns>
        <Columns Title = "Pos___" Field="position" Merge="left" Align="right" ></Columns>
        <Columns Index="true" Title = "Callsign" Field ="call" Align = "left" ></Columns>
        <Columns Title = "Loc" Field ="locator" Align = "center" ></Columns>
        <Columns Title = "QSOS" Field = "Qs" Align = "right" ></Columns>
        <Columns Title = "Score" Field="score" Align = "right" ></Columns>
        <Columns Title = "ODX" Field="ODXCall" Align = "center" ></Columns>
        <Columns Title = "Kms" Field="ODXKms" Align = "center" ></Columns>
        <Columns Title = "Power" Field="power" Align = "center" ></Columns>
        <Columns Title = "Group" Field="clubName" Align = "center" Sections= "O"></Columns>
        <Columns Title = "Operators" Field="Operators" Align = "left" Sections= "O" ></Columns>
        <Columns Title = "Ant" Field="ant" Align = "center"  img="tower.gif" ></Columns>
        <Columns Title = "Equipment" Field="equipment" Align = "center" img="tx.gif" ></Columns>
        <Columns Title = "Comments" Field="SoapBox" Align = "left" img="soapbox.gif" ></Columns>
</ColumnFormat>
<ColumnFormat>
        <name>vhfafs</name>
        <Columns Title = "Certificate Winner" Nocolumn="true" Merge="right" Field="cert" img="cert.gif" ></Columns>
        <Columns Title = "Pos___" Field="position" Merge="left" Align="right" ></Columns>
        <Columns Index="true" Title = "Callsign" Field ="call" Align = "left" ></Columns>
        <Columns Title = "Loc" Field ="locator" Align = "center" ></Columns>
        <Columns Title = "QSOS" Field = "Qs" Align = "right" ></Columns>
        <Columns Title = "Score" Field="score" Align = "right" ></Columns>
        <Columns Title = "ODX" Field="ODXCall" Align = "center" ></Columns>
        <Columns Title = "Kms" Field="ODXKms" Align = "center" ></Columns>
        <Columns Title = "Power" Field="power" Align = "center" ></Columns>
        <Columns Title = "Group" Field="clubName" Align = "center" ></Columns>
        <Columns Title = "Operators" Field="Operators" Align = "left" Sections= "O" ></Columns>
        <Columns Title = "Ant" Field="ant" Align = "center"  img="tower.gif" ></Columns>
        <Columns Title = "Equipment" Field="equipment" Align = "center" img="tx.gif" ></Columns>
        <Columns Title = "Comments" Field="SoapBox" Align = "left" img="soapbox.gif" ></Columns>
</ColumnFormat>
<statsFormat>
<name>afs</name>
<section_list>SF</section_list>
<section_list>O</section_list>
<columns Title = "Qs" Field="RealAnyQs" ></columns>
<columns Title = "Points" Field="RealAnyDx"></columns>
</statsFormat>
<statsFormat>
<name>ukac</name>
<section_list>Totals</section_list>
<columns Title = "Qs" Field="RealAnyQs" ></columns>
<columns Title = "Mults" Field="AnyMults"></columns>
</statsFormat>
<statsFormat>
<name>dummy</name>
<section_list>ALL</section_list>
<columns Title = "Qs" Field="RealAnyQs" ></columns>
</statsFormat>
<resultsFormatType>
        <name>vhfnfdres</name>
        <ColumnFormatUsed>vhfnfd</ColumnFormatUsed>
        <cumulativeField>Norm</cumulativeField>
        <normType>1000UK</normType>
		<special>centenary</special>
        <ScoresCount>4</ScoresCount>
</resultsFormatType>
<resultsFormatType>
        <name>multiband2</name>
        <ColumnFormatUsed>vhfnorm</ColumnFormatUsed>
        <cumulativeField>Norm</cumulativeField>
        <normType>1000</normType>
</resultsFormatType>
<resultsFormatType>
        <name>group</name>
        <ColumnFormatUsed>vhfgroup</ColumnFormatUsed>
</resultsFormatType>
<resultsFormatType>
        <name>4mcum</name>
        <ColumnFormatUsed>vhf</ColumnFormatUsed>
        <cumulativeField>Norm</cumulativeField>
        <normType>1000UK</normType>
        <ScoresCount>3</ScoresCount>
</resultsFormatType>
<resultsFormatType>
        <name>vhfukac</name>
        <ColumnFormatUsed>vhfmultsandnorm</ColumnFormatUsed>
        <cumulativeField>Norm</cumulativeField>
        <normType>Pos</normType>
        <ScoresCount>8</ScoresCount>
        <StatsFormatUsed>ukac</StatsFormatUsed>
</resultsFormatType>
<resultsFormatType>
        <name>shfukac</name>
        <ColumnFormatUsed>vhfmultsandnorm</ColumnFormatUsed>
        <cumulativeField>Norm</cumulativeField>
        <normType>Pos</normType>
        <ScoresCount>8</ScoresCount>
	<useContestID>SHF UKAC</useContestID>
</resultsFormatType>
<resultsFormatType>
        <name>xmasfun</name>
        <ColumnFormatUsed>xmasresults</ColumnFormatUsed>
        <cumulativeField>Norm</cumulativeField>
        <normType>1000UK</normType>
        <ScoresCount>3</ScoresCount>
	<useContestID>Christmas Cumulatives</useContestID>
</resultsFormatType>
<resultsFormatType>
        <name>vhfmults</name>
        <ColumnFormatUsed>vhfmults</ColumnFormatUsed>
</resultsFormatType>
<resultsFormatType>
        <name>vhfnomults</name>
        <ColumnFormatUsed>vhf</ColumnFormatUsed>
</resultsFormatType>
<resultsFormatType>
        <name>vhfafsmults</name>
        <ColumnFormatUsed>vhfmultsandnorm</ColumnFormatUsed>
        <TeamSize>4</TeamSize>
        <cumulativeField>vhfafs</cumulativeField>
        <normType>vhfafs</normType>
</resultsFormatType>
<resultsFormatType>
        <name>vhfafs</name>
        <ColumnFormatUsed>vhfafs</ColumnFormatUsed>
        <TeamSize>4</TeamSize>
        <cumulativeField>vhfafs</cumulativeField>
        <normType>vhfafs</normType>
        <StatsFormatUsed>afs</StatsFormatUsed>
</resultsFormatType>
<special_rule>
<name>S1</name>
<description>1 Point per QSO</description>
<long_description>
Scores will be calculated at 1 point / QSO.
</long_description>
</special_rule>
<special_rule>
<name>S2</name>
<description>Deleted</description>
<long_description>
No longer used
</long_description>
</special_rule>
<special_rule>
<name>S3</name>
<description>Affiliated Societies contest </description>
<long_description>
This is an Affiliated Societies contest and is open to both individual entrants (who must be RSGB members), and to teams made up of a number of operators who must all be members of the same affiliated society, but not necessarily RSGB members themselves.   

The results from the 6m, 2m and 70cm Affiliated Society contests contribute to the AFS Super League. http://www.rsgbcc.org/hf/rules/2012/AFS-SuperLeague2012-2013.shtml

a. All members of the team must operate from within 50 miles of the normal meeting place of the society and must be within the UK. No station may represent more than one society. No operator is allowed to use more than one callsign during the contest. In the case of national societies, each team must define a separate meeting place , and each team member must operate within 50 miles of that designated meeting place.

b. QSOs with other members of your team will count for points.

c. Each AFS member will be allocated to one or more teams in descending order of adjudicated score. For the purpose of calculating the overall AFS team score, each member of each team will be placed in one of 4 sections. Sections A, B, C etc. The highest placed member of each team will be placed in Section A, the second highest in Section B etc. All stations in each of the sections will have their score normalised against the highest score in that section, with the highest score gaining 1000 points. The final AFS team score will be the sum of the team members individual normalised scores.

d. Logs must be uploaded individually, using an AFS Club Name chosen from the list on the contest entry robot. The RSGB Contest Committee verifies that distance rules are being complied with. Therefore the address, including postcode or QTH locator of the normal meeting place of each club must be emailed to afs.query@rsgbcc.org. This only needs to be done once for each club, after which the information will be kept on file. The currently held address information can viewed and verified during AFS log submission.  Additions to the robot club names list or changes to the club meeting place data should be emailed to afs.query@rsgbcc.org
</long_description>
</special_rule>
<special_rule>
<name>S4</name>
<description>Runs concurrently with a backpackers contest</description>
<long_description>
This contest runs concurrently with a backpackers contest. Stations entering the backpackers contest only may be worked once from a fixed location and once from their portable location for points.
</long_description>
</special_rule>
<special_rule>
<name>S5</name>
<description>Cumulative contest</description>
<long_description>
Scores will be normalised for each band/session as follows. 
Score for each band/session = (Score achieved x 1000) divded by (Band/session leader score).
For cumulative contests the overall score will normally be calculated from the best 3 normalised session scores 
It is impossible for you to determine your best sessions without knowing everyone else's scores, so please submit your logs and scores from all sessions in which you were active and allow the adjudicator to calculate your best sessions.

Stations may move location between individual cumulative activity periods
</long_description>
</special_rule>
<special_rule>
<name>S6</name>